### ISSUE TITLE
Guid NULL Check

### ISSUE THREAD

**Issue by sridharrajan** [fluentsprings/ExpressMapper#96] opened 2016-05-17 05:38 UTC
Hi anisimovyuriy,

You are doing excellent work. Thanks a lot.

I want to throw exception for null values.

public class GuidCustomMapper : ICustomTypeMapper<string, Guid>
{

        public Guid Map(IMappingContext<string, Guid> context)
        {
            if (string.IsNullOrEmpty(context.Source))
            {
                throw new ArgumentException("Unable to Convert Null/Empty string to GUID");
            }
            return Guid.Parse(context.Source);
        }
 }

Mapper.RegisterCustom\<string, Guid, GuidCustomMapper>();

Above code working fine for string.empty value. But not for null string it is converting to 00000000-0000-0000-0000-000000000000. How can i achieve? Please help me.

**Comment by anisimovyuriy** [comment] 2016-05-17 05:45
Hi @sridharrajan,

Thanks a lot for appreciation and valuable input.
hmm very strange as it should work as you defined.
context.Source is string that can be string.Empty and null - it works for context.Source being string.empty but not for null? Have you tried to debug your GuidCustomMapper when context.Source == null?
Anyway I'll try to reproduce and get back to you.

Thanks,
Yuriy

**Comment by sridharrajan** [comment] 2016-05-17 08:20
[SriSample.zip](https://github.com/fluentsprings/ExpressMapper/files/267669/SriSample.zip)

Hi anisimovyuriy,

Thanks for your quick response.
I have attached sample console application which I tried. Please use it for verification.

**Comment by high1** [comment] 2016-06-12 06:59
I have a very similar issue with RegisterCustom - basically, I register a custom mapping for decimal to string which is working as it should, but when a decimal is 0.00 - default value, I get a null string in mapping, where it should be "0.00". If you need a test case, let me know - I'm writing here, because I the root of both issues is the same.

**Comment by anisimovyuriy** [comment] 2016-06-27 02:12
Fixed! Will be included in 1.8.5 release! Thanks a lot for your contribution @sridharrajan!

**Closed by anisimovyuriy** 2016-06-27 02:12 UTC
Labels: bug

**Comment by sridharrajan** [comment] 2016-09-14 04:31
Sorry!!

I hope this issue is fixed in V1.8.2. But it is still converting to 00000000-0000-0000-0000-000000000000 instead of throwing exception. Please let me know this issue is fixed in V1.8.2

[SriSample2.zip](https://github.com/fluentsprings/ExpressMapper/files/471277/SriSample2.zip)
